version: "3"

services:
  auth_service:
    build:
      context: ./../
      dockerfile: ./Dockerfile
    ports:
    - 8081:8081
    environment:
      APP_ENV: production
    networks:
      lsu_network:
        ipv4_address: 192.168.0.6

networks:
  lsu_network:
    external: true